laba1:
	@echo "Выполнение первой лабы..."
	@python3 db_manager.py 1

laba2:
	@echo "Выполнение второй лабы..."
	@python3 db_manager.py 2

laba3:
	@echo "Выполнение третьей лабы..."
	@python3 db_manager.py 3

install:
	@echo "  Установка нужных модулей Python..."
	@pip -q install -r requirements.txt