version: '2.10.2'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data

  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/monodb:/data

  neo4j:
    image: neo4j:latest
    hostname: jewestyes
    container_name: myneo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/jewestyes
      NEO4J_dbms_logs_debug_level: DEBUG

  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: elasticsearch

    networks:
      elastic:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: jewestyes
      POSTGRES_PASSWORD: jewestyes
    ports:
      - "5432:5432"

networks:
  elastic:
    driver: bridge
